name: Gradle Wrapper Validation
  uses: gradle/wrapper-validation-action@v3.5.0
  with:
    # Minimum number expected gradle-wrapper.jar files found in the repository. Non-negative number. Higher number is useful in monorepos where each project might have their own wrapper.
    min-wrapper-count: # optional, default is 1
    # Allow Gradle snapshot versions during checksum verification. Boolean, true or false.
    allow-snapshots: # optional, default is false
    # Accept arbitrary user-defined checksums as valid. Comma separated list of SHA256 checksums (lowercase hex).
    allow-checksums: # optional, default is 
  on: [push, pull_request]

  jobs:
    validation:
      name: "Validation"
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: gradle/wrapper-validation-action@v3
